nginx-main:
  image: nginx
  ports:
      - "8080:8080"
  volumes:
      - ./nginx-main/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-dashboard/build:/usr/share/nginx/html
  links:
    - api-user
    - frontend-dashboard
    - api-scheduler

frontend-dashboard:
  image: node:carbon
  command: bash -c "npm install && npm start"
  working_dir: /app
  volumes:
    - ./frontend-dashboard:/app
  environment:
    PORT: 8080
  ports:
    - "8002:8080"
