api-user:
  image: node:carbon
  command: bash -c "npm install && npm start"
  working_dir: /app
  volumes:
    - ./api-user:/app
  environment:
    PORT: 9000
  ports:
    - "9000:9000"
  links:
    - mongodb
#
#frontend:
#  image: node:7
#  command: npm run webpack
#  working_dir: /app
#  volumes:
#    - ./frontend:/app
#  ports:
#    - "4000:4000"
#
nginx-main:
  image: nginx
  ports:
      - "8080:8080"
  volumes:
      - ./nginx-main/default.conf:/etc/nginx/conf.d/default.conf
#      - ./frontend/dist:/usr/share/nginx/html
  links:
    - api-user

mongodb:
  image: mongo
  ports:
      - "27017:27017"
