api-user:
  image: node:carbon
  command: bash -c "npm install && npm start"
  working_dir: /app
  volumes:
    - ./api-user:/app
  environment:
    PORT: 9000
  ports:
    - "8001:9000"
  links:
    - mongodb

frontend-dashboard:
  image: node:carbon
  command: bash -c "npm install && npm start"
  working_dir: /app
  volumes:
    - ./frontend-dashboard:/app
  environment:
    PORT: 8080
  ports:
    - "8002:8080"

nginx-main:
  image: nginx
  ports:
      - "8000:8080"
  volumes:
      - ./nginx-main/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-dashboard/build:/usr/share/nginx/html
  links:
    - api-user
    - frontend-dashboard

mongodb:
  image: mongo
  ports:
      - "27017:27017"
