nginx-main:
  image: nginx
  ports:
      - "8080:8080"
  volumes:
      - ./nginx-main/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-dashboard/build:/usr/share/nginx/html
  links:
    - api-user
    - api-starter
    - frontend-dashboard

api-user:
  image: node:carbon
  command: bash -c "npm install && npm start"
  working_dir: /app
  volumes:
    - ./api-user:/app
  environment:
    PORT: 8080
  ports:
    - "8001:8080"
  links:
    - mongodb

frontend-dashboard:
  image: node:carbon
  command: bash -c "npm install && npm start"
  working_dir: /app
  volumes:
    - ./frontend-dashboard:/app
  environment:
    PORT: 8080
  ports:
    - "8002:8080"

api-chat:
  image: node:carbon
  command: bash -c "npm install && npm start"
  working_dir: /app
  volumes:
    - ./api-chat:/app
  environment:
    PORT: 8080
  ports:
    - "8003:8080"
  links:
    - mongodb


mongodb:
  image: mongo
  ports:
      - "27017:27017"
