service: serverless-rest-api-with-dynamodb

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline


custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
        domain:
          sources:
            - table: consultUser
              sources: [./dynamodbTest/consultUserTable.json]
            - table: serverless-rest-api-with-dynamodb-dev
              sources: [./dynamodbTest/eventTable.json]
            - table: UserEventMapper
              sources: [./dynamodbTest/UserEventMapperTable.json]

    migration:
      dir: offline/migrations
    webpack:
      IncludeModules: true

provider:
  name: aws
  region: us-west-2
  runtime: nodejs6.10
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    CONSULT_TABLE: consultUser
    USER_EVENT_MAPPER_TABLE: UserEventMapper


  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CONSULT_TABLE}"

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USER_EVENT_MAPPER_TABLE}"


functions:
  CreateScheduler:
    handler: scheduler/create.create
    events:
      - http:
          path: schedule
          method: post
          cors: true

  ListScheduler:
    handler: scheduler/list.list
    events:
      - http:
          path: schedule
          method: get
          cors: true

  GetScheduler:
    handler: scheduler/get.get
    events:
      - http:
          path: schedule/{id}
          method: get
          cors: true

  UpdateScheduler:
      handler: scheduler/update.update
      events:
        - http:
            path: schedule
            method: put
            cors: true

  DeleteSchedular:
      handler: scheduler/delete.delete
      events:
        - http:
            path: schedule
            method: delete
            cors: true

  UpdateEventSchedule:
          handler: scheduler/eventSchedule.update
          events:
            - http:
                path: user/event/schedule
                method: put
                cors: true


  updateProfile:
      handler: user/profile/update.update
      events:
        - http:
            path: user/profile
            method: put
            cors: true

  UserCreate:
      handler: user/create.create
      events:
        - http:
            path: user
            method: post
            cors: true

  GetAuthUserInitData:
      handler: user/get.get
      events:
        - http:
            path: user
            method: get
            cors: true
  GetFreeEventsFromUser:
      handler: user/event/free/get.get
      events:
        - http:
            path: user/event/free
            method: get
            cors: true
  GetUserNextEvent:
      handler:  user/event/next/get.get
      events:
        - http:
            path: user/event/next
            method: get
            cors: true
  GetConsultants:
    handler:  admin/consultant/list.list
    events:
      - http:
          path: admin/consultant
          method: get
          cors: true


  TestAuthToken:
          handler: scheduler/test.create
          events:
            - http:
                path: scheduler/test
                method: post
                cors: true
  JwtDecorde:
        handler: jwtTokenDecorder/get.get
        events:
          - http:
              path: jwt
              method: get
              cors: true


resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

    UserDynamoDbTable:
          Type: 'AWS::DynamoDB::Table'
          DeletionPolicy: Retain
          Properties:
            AttributeDefinitions:
              -
                AttributeName: id
                AttributeType: S
            KeySchema:
              -
                AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            TableName:  ${self:provider.environment.CONSULT_TABLE}


    UserEventMapperDynamoDbTable:
              Type: 'AWS::DynamoDB::Table'
              DeletionPolicy: Retain
              Properties:
                AttributeDefinitions:
                  -
                    AttributeName: id
                    AttributeType: S
                  -
                    AttributeName: date
                    AttributeType: S
                KeySchema:
                  -
                    AttributeName: id
                    KeyType: HASH
                  -
                    AttributeName: date
                    KeyType: RANGE
                ProvisionedThroughput:
                  ReadCapacityUnits: 1
                  WriteCapacityUnits: 1
                TableName:  ${self:provider.environment.USER_EVENT_MAPPER_TABLE}

